### ISSUE TITLE
make: *** No targets specified and no makefile found.

### ISSUE THREAD

**Issue by claus-h-g** [CMU-SAFARI/SneakySnake#4]
Hello,
Many thanks for providing SneakySnake.
On a xUbuntu18.04 machine with a singe user called minknow I tried to follow your instruction for getting started.
I did run:
in my home directory
 git clone https://github.com/CMU-SAFARI/SneakySnake
Cloning into 'SneakySnake'...
remote: Enumerating objects: 649, done.
remote: Counting objects: 100% (66/66), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 649 (delta 29), reused 56 (delta 23), pack-reused 583
Receiving objects: 100% (649/649), 20.87 MiB | 10.79 MiB/s, done.
Resolving deltas: 100% (268/268), done.
minknow@meqneuropat24:~$ cd SneakySnake && make

and obtained this error:
make: *** No targets specified and no makefile found.  Stop.

Frankly speaking I am not sure where to get started fixing this. 
Could you please guide me to a solution?

Many thanks.

**Comment by mealser** [comment]
Thanks for your question.
You need to be inside the SneakySnake folder that is inside the SneakySnake repo.
So please use one of the following commands:

```
cd SneakySnake/SneakySnake && make

make -C SneakySnake/SneakySnake
```

I updated the README to make this clear.

Thanks.

**Comment by claus-h-g** [comment]
Many thanks for your rapid reply. I highly appreciate your help.

Unfortunately I did run into the next issue:

cd SneakySnake/SneakySnake && make
gcc -g -O3 -Wall -o main kthread.c SneakySnake.c main.c -lz -lm -pthread
main.c: In function ‘worker_for’:
main.c:96:6: warning: unused variable ‘banded’ [-Wunused-variable]
  int banded=1;
      ^~~~~~
main.c:95:6: warning: unused variable ‘n’ [-Wunused-variable]
  int n=0;
      ^
main.c: In function ‘main’:
main.c:160:17: warning: unused variable ‘banded’ [-Wunused-variable]
             int banded=1;
                 ^~~~~~
main.c:159:17: warning: unused variable ‘n’ [-Wunused-variable]
             int n=0;
                 ^
main.c:130:10: warning: variable ‘read’ set but not used [-Wunused-but-set-variable]
  ssize_t read;

**Comment by mealser** [comment]
These are warnings that you can ignore.
Please run the next command and let me know if all is good.

**Comment by claus-h-g** [comment]
I did run:
~/SneakySnake/SneakySnake$ ./main 0 100 100 100 Datasets/ERR240727_1_E2_30000Pairs.txt 30000 10 10

Output is:
This system has 8 processors configured and 8 processors available.
Data: Datasets/ERR240727_1_E2_30000Pairs.txt	Threads: 10	E: 10	Accepted: 28803	Rejected:1197	Time: 8 milliseconds

so far I was not clear what to expect. Please let me know if the output is correct.

**Comment by mealser** [comment]
At most, you can use up to 8 threads based on your machine.
You can see the intermediate calculations using the debug mode.
So far it seems you don't have any issues with running it, so I am closing this.

Thanks for your follow-ups.
