### ISSUE TITLE
Unequal sequence lengths?

### ISSUE THREAD

**Issue by brendanf** [CMU-SAFARI/SneakySnake#5]
I'm interested in trying out SneakySnake, but as far as I can tell,  aligning sequences with unequal lengths is not directly supported in the main `SneakySnake()` function.  Is this an inherent limitation of the algorithm, or is it something which could be added without much effort? Especially for long reads, it seems quite uncommon to need to align (or pre-filter) a set of sequences which are all exactly the same length.

**Comment by mealser** [comment]
Hi Brendan,
Thanks for your interest. 
Supporting unequal lengths is not a limitation of the algorithm.
The current implementation of SneakySnake follows what most read mappers (including minimap2) do, which is requiring the first k characters (k-mer) of both sequences to be exactly matching. This is a semi-global fashion. If you have such sequences, then you just need to run SneakySnake with a sequence length equal to the minimum length of the two input sequences and it should work directly. If you don't have such sequences, you could pad the shortest sequence with, for example, A's and run SneakySnake as usual. It should also work well assuming you choose the appropriate edit distance threshold value. 

I am curious to know how it goes with you and I can update the main function accordingly if needed.
Thanks.

**Comment by brendanf** [comment]
Ok, I think I understand. I've never actually looked in to how read mappers work.  In my case, I am calculating pairwise distances using fully global alignment between metabarcoding amplicon reads, so I know (because of the primer locations) that the start and end of both sequences should align. However there are usually indels between, so the read lengths are not the same.  The ideal case for me would be a fully global version of the algorithm, which also allows unequal read lengths.

But since the current implementation is semi-global, then it sounds like, if I follow your suggestion to pad the end of the shorter sequence with As, then because they would typically be "aligned" to an end gap on the other sequence, then the edit distance calculated by SneakySnake would not include them?  In that case it sounds like it could work; I will after all use a full aligner on the sequence pairs which pass SneakySnake. I'll at least give it a shot to see whether it filters out enough read pairs to save total execution time in my test data.
